var phrases = [
    "Lovin' you is easy <br> 'cause you're... You.",
    "Someday you'll forget the world out there, so live a life you'll remember",
    "Family is the one who respects you, your life and your choices. Your blood even mosquito has, so don't accept defamation just because they're your family.",
    "Don't let the universe take you where it wants, these decisions are you who must make it yourself.",
    "The past is a line and the future is infinite by its possibilities. Don't be sorry for the bad decisions you've made, make the right ones from now on.",
    "The things that excite you are not random.<br> They are connected to your purpose.<br> Follow them.",
    "The cause of defeat is caused more by the lack of determination of the person himself than by the obstacles or rigor of circumstances, so stand up and believe in your potential",
    "Be very good, that they won't be going to be any way to ignore you.",
    "The secret of failure is to try to please everyone, so start thinking about yourself first and help as much as possible... We're human, not machines.",
    "To be successful, the desire for success must be greater than the fear of failure.",
    "Twenty years from now, you won't regret the things you've done, but the things you've failed to do. So sail away from your safe haven. Get the winds. Explore. Dream on. Discover",
    "Your struggle doesn't end when you feel tired, but when you achieve the success you deserve",
    "Take a chance, go ahead and fearless! There's no greater motivation than figuring out how brave we can be.",
    "There are days when you have to move on with just what you have on hand, you can't wait for motivation.",
    "Problems are opportunities to show what you know.",
    "Our failures are sometimes more fruitful than our successes.",
    "It's a fool's custom, when he makes mistakes, to complain about others.<br> It's a wise man's custom to complain about himself.",
    "True heroism is to persist a little longer, when all seems lost.",
    "Even if you've already taken a long walk, there's always a new way to go.",
    "In prosperity, our friends know us; in adversity, we know our friends.",
    "It's always fun to do the impossible.",
    "Always remember that your will to triumph is more important than anything else.",
    "Experience is the name that everyone should give to their mistakes.",
    "The only place that success comes before work is in the dictionary.",
    "We are what we do over and over again. Therefore, excellence is not an achievement, it is a habit",
    "Don't expect the opportunities to come to you, go to them!",
    "I've always been afraid to make wrong decisions in my life until I understand how life is too short to be afraid.",
    "Self-respect, self-knowledge and self-control lead life to supreme power.",
    "Nothing important in the world was accomplished without passion.",
    "If you can't stand out for talent, win by effort.",
    "Don't let the noise of others' opinions drown out your own inner voice.",
    "Only those who dare to make many mistakes can accomplish much.",
    "Accept the challenges so you can feel the taste of victory.",
    "Luck favors the prepared mind.",
    "Goals are necessary not only to motivate us, but to keep us alive.",
    "People with goals succeed because they know where they're going.",
    "There is no success without difficulty.",
    "A great pleasure in life is to do what they say you are not able to do.",
    "All glory comes from daring to begin with.",
    "The person who doesn't believe in himself doesn't believe in anything else.",
    "Great minds are ready not only to explore opportunities, but to create them.",
    "The first indispensable step to achieve things in life is to decide what you want.",
    "The greatest reward for work is not what the person earns, it is what he becomes through it.",
    "When expectations rise, an endless and continuous cycle of improvement begins.",
    "The one who made a mistake and didn't correct is making another mistake.",
    "What deserves to be done deserves to be done well.",
    "Don't slow down your progress for fear of failure.",
    "He who dominates others is strong; he who dominates himself is all-powerful.",
    "The real risk is that you don't do anything.",
    "Risking anything is risking everything.",
    "Happiness is not something ready. It comes from your own actions.",
    "The present is the only time we have to do anything.",
    "It's good to let the mind relax once in a while.",
    "You feel suffocated by the one without a life goal.",
    "People only see what they're prepared to see.",
    "Those who live without discipline die without honor.",
    "You have to do the things you think you won't be able to do.",
    "Our doubts are traitorous and make us lose, for fear of trying, what we could win.",
    "Do what you can, with what you have, wherever you are.",
    "What is thought about you indicates your destiny.",
    "We must be the change we want to see in the world.",
    "In any initiative, consider where you can go."
]